#!/bin/bash

# TODO: allow to turn off colors

BWHITE="\033[1;37m"
BYELLOW="\033[1;33m"
BBLUE="\033[1;34m"
BRED="\033[1;31m"

# workaround to turn off colors
NOCOLOR=""

COLOR_OFF="\033[0m"

LOG_TAG="write-log"
if [ -z "$LOG_TAG_COLOR" ]; then
	# LOG_TAG_COLOR=$BWHITE
	LOG_TAG_COLOR=$NOCOLOR
fi
# LOG_TEXT_COLOR=$BYELLOW
# LOG_TEXT_COLOR=$BRED
if [ -z "$LOG_TEXT_COLOR" ]; then
	# LOG_TEXT_COLOR=$BBLUE
	LOG_TEXT_COLOR=$NOCOLOR
fi
LOG_COLOR_OFF=$COLOR_OFF

write_log_color() {
        echo -en $LOG_TAG_COLOR$LOG_TAG: $LOG_TEXT_COLOR "$1"$LOG_COLOR_OFF
}

write_log() {
        write_log_color "$1"
}

# TODO: let the user to configure colors
while getopts "t:T:" i; do
	case $i in
		"t")
			TXT_COLOR=$OPTARG
			;;
		"T")
			TAG_COLOR=$OPTARG
			;;
	esac
done
shift "$((OPTIND - 1))"

if [ -n "$TXT_COLOR" ]; then
	case $TXT_COLOR in
		"blue")
			LOG_TEXT_COLOR=$BBLUE
		;;
		"red")
			LOG_TEXT_COLOR=$BRED
		;;
		"yellow")
			LOG_TEXT_COLOR=$BYELLOW
		;;
		"white")
			LOG_TEXT_COLOR=$BWHITE
		;;
	esac
fi

if [ -n "$TAG_COLOR" ]; then
	case $TAG_COLOR in
		"blue")
			LOG_TAG_COLOR=$BBLUE
		;;
		"red")
			LOG_TAG_COLOR=$BRED
		;;
		"yellow")
			LOG_TAG_COLOR=$BYELLOW
		;;
		"white")
			LOG_TAG_COLOR=$BWHITE
		;;
	esac
fi

if [ -n "$2" ]; then
	LOG_TAG=${2}
fi

write_log "$1"
